ALTER TABLE resi_pengiriman
  ADD COLUMN IF NOT EXISTS cnote_no    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS service     TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS tujuan      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS penerima    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS barang      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS ongkir      INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS jam_kirim   TEXT DEFAULT '';
